[rospy.client][INFO] 2017-10-18 07:46:03,355: init_node, name[/state_follow_waypoint], pid[27597]
[xmlrpc][INFO] 2017-10-18 07:46:03,356: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2017-10-18 07:46:03,362: ROS Slave URI: [http://10.0.0.116:40658/]
[xmlrpc][INFO] 2017-10-18 07:46:03,363: Started XML-RPC server [http://10.0.0.116:40658/]
[rospy.impl.masterslave][INFO] 2017-10-18 07:46:03,363: _ready: http://10.0.0.116:40658/
[xmlrpc][INFO] 2017-10-18 07:46:03,373: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-10-18 07:46:03,380: Registering with master node http://10.0.0.116:11311
[rospy.init][INFO] 2017-10-18 07:46:03,463: registered with master
[rospy.rosout][INFO] 2017-10-18 07:46:03,464: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-18 07:46:03,485: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-18 07:46:03,493: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-18 07:46:03,619: topic[/state_command] adding connection to [http://10.0.0.116:40658/], count 0
[rospy.internal][INFO] 2017-10-18 07:46:03,636: topic[/state_command] adding connection to [http://10.0.0.116:33171/], count 1
[rospy.internal][INFO] 2017-10-18 07:46:03,651: topic[/state_command] adding connection to [/state_follow_waypoint], count 0
[rospy.internal][INFO] 2017-10-18 07:46:03,729: topic[/state_command] adding connection to [/state_driving_away], count 1
[rospy.internal][INFO] 2017-10-18 07:46:03,738: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-18 07:46:04,111: topic[/state_command] adding connection to [http://10.0.0.116:37475/], count 2
[rospy.internal][INFO] 2017-10-18 07:46:04,201: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 2
[rospy.internal][INFO] 2017-10-18 07:46:04,289: topic[/state_command] adding connection to [http://10.0.0.116:43499/], count 3
[rospy.internal][INFO] 2017-10-18 07:46:04,312: topic[/state_command] adding connection to [/state_driving_to_cone], count 3
[rospy.internal][INFO] 2017-10-18 07:46:05,707: topic[/mavros/local_position/pose] adding connection to [http://10.0.0.116:35943/], count 0
[rospy.internal][INFO] 2017-10-18 07:46:05,758: topic[/mavros/setpoint_raw/target_local] adding connection to [http://10.0.0.116:35943/], count 0
[rospy.internal][INFO] 2017-10-18 07:46:05,837: topic[/mavros/state] adding connection to [http://10.0.0.116:35943/], count 0
[rospy.internal][INFO] 2017-10-18 07:46:05,910: topic[/mavros/battery] adding connection to [http://10.0.0.116:35943/], count 0
[rospy.internal][INFO] 2017-10-18 07:46:05,913: topic[/mavlink/from] adding connection to [http://10.0.0.116:35943/], count 0
[rospy.internal][INFO] 2017-10-18 07:46:06,254: topic[/mavros/rc/override] adding connection to [/mavros], count 0
[rospy.internal][INFO] 2017-10-18 07:46:06,283: topic[/mavros/mission/waypoints] adding connection to [http://10.0.0.116:35943/], count 0
[rospy.internal][INFO] 2017-10-18 07:46:06,326: topic[/state_command] adding connection to [http://10.0.0.116:34779/], count 4
[rospy.internal][INFO] 2017-10-18 07:46:06,337: topic[/exec_command] adding connection to [/exec], count 0
[rospy.core][INFO] 2017-10-18 07:46:20,543: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-10-18 07:46:20,718: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-18 07:46:20,719: topic[/mavros/rc/override] removing connection to /mavros
[rospy.internal][INFO] 2017-10-18 07:46:20,722: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][INFO] 2017-10-18 07:46:20,724: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][INFO] 2017-10-18 07:46:20,724: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][ERROR] 2017-10-18 07:46:20,723: Unable to initiate TCP/IP socket to 10.0.0.116:42912 (http://10.0.0.116:40658/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:46:20,726: topic[/state_command] removing connection to /state_driving_to_cone
[rospy.internal][INFO] 2017-10-18 07:46:20,731: topic[/exec_command] removing connection to /exec
[rospy.internal][ERROR] 2017-10-18 07:46:20,734: Unable to initiate TCP/IP socket to 10.0.0.116:39276 (http://10.0.0.116:37475/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:46:20,733: topic[/mavros/mission/waypoints] removing connection to http://10.0.0.116:35943/
[rospy.internal][INFO] 2017-10-18 07:46:20,737: topic[/mavros/state] removing connection to http://10.0.0.116:35943/
[rospy.internal][INFO] 2017-10-18 07:46:20,738: topic[/mavlink/from] removing connection to http://10.0.0.116:35943/
[rospy.internal][INFO] 2017-10-18 07:46:20,738: topic[/mavros/local_position/pose] removing connection to http://10.0.0.116:35943/
[rospy.internal][INFO] 2017-10-18 07:46:20,741: topic[/mavros/battery] removing connection to http://10.0.0.116:35943/
[rospy.internal][INFO] 2017-10-18 07:46:20,742: topic[/state_command] removing connection to http://10.0.0.116:40658/
[rospy.internal][INFO] 2017-10-18 07:46:20,743: topic[/state_command] removing connection to http://10.0.0.116:33171/
[rospy.internal][INFO] 2017-10-18 07:46:20,744: topic[/state_command] removing connection to http://10.0.0.116:37475/
[rospy.internal][INFO] 2017-10-18 07:46:20,747: topic[/state_command] removing connection to http://10.0.0.116:43499/
[rospy.internal][INFO] 2017-10-18 07:46:20,750: topic[/state_command] removing connection to http://10.0.0.116:34779/
[rospy.internal][INFO] 2017-10-18 07:46:20,751: topic[/mavros/setpoint_raw/target_local] removing connection to http://10.0.0.116:35943/
[rospy.impl.masterslave][INFO] 2017-10-18 07:46:20,752: signal-2
[rospy.internal][ERROR] 2017-10-18 07:46:20,754: Unable to initiate TCP/IP socket to 10.0.0.116:42387 (http://10.0.0.116:34779/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2017-10-18 07:46:21,178: signal_shutdown [atexit]
