[rospy.client][INFO] 2017-10-18 07:46:03,829: init_node, name[/state_avoiding_obstacle], pid[27627]
[xmlrpc][INFO] 2017-10-18 07:46:03,835: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-10-18 07:46:03,836: Started XML-RPC server [http://10.0.0.116:37475/]
[rospy.impl.masterslave][INFO] 2017-10-18 07:46:03,837: _ready: http://10.0.0.116:37475/
[xmlrpc][INFO] 2017-10-18 07:46:03,847: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2017-10-18 07:46:03,858: ROS Slave URI: [http://10.0.0.116:37475/]
[rospy.registration][INFO] 2017-10-18 07:46:03,870: Registering with master node http://10.0.0.116:11311
[rospy.init][INFO] 2017-10-18 07:46:03,959: registered with master
[rospy.rosout][INFO] 2017-10-18 07:46:03,959: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-18 07:46:03,967: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-18 07:46:03,981: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-18 07:46:04,119: topic[/state_command] adding connection to [/state_follow_waypoint], count 0
[rospy.internal][INFO] 2017-10-18 07:46:04,132: topic[/state_command] adding connection to [/state_driving_away], count 1
[rospy.internal][INFO] 2017-10-18 07:46:04,168: topic[/state_command] adding connection to [http://10.0.0.116:33171/], count 0
[rospy.internal][INFO] 2017-10-18 07:46:04,176: topic[/state_command] adding connection to [http://10.0.0.116:40658/], count 1
[rospy.internal][INFO] 2017-10-18 07:46:04,185: topic[/state_command] adding connection to [http://10.0.0.116:37475/], count 2
[rospy.internal][INFO] 2017-10-18 07:46:04,188: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-18 07:46:04,200: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 2
[rospy.internal][INFO] 2017-10-18 07:46:04,257: topic[/state_command] adding connection to [http://10.0.0.116:43499/], count 3
[rospy.internal][INFO] 2017-10-18 07:46:04,309: topic[/state_command] adding connection to [/state_driving_to_cone], count 3
[rospy.internal][INFO] 2017-10-18 07:46:05,516: topic[/mavros/local_position/pose] adding connection to [http://10.0.0.116:35943/], count 0
[rospy.internal][INFO] 2017-10-18 07:46:05,590: topic[/mavros/setpoint_raw/target_local] adding connection to [http://10.0.0.116:35943/], count 0
[rospy.internal][INFO] 2017-10-18 07:46:05,734: topic[/mavros/state] adding connection to [http://10.0.0.116:35943/], count 0
[rospy.internal][INFO] 2017-10-18 07:46:05,740: topic[/mavlink/from] adding connection to [http://10.0.0.116:35943/], count 0
[rospy.internal][INFO] 2017-10-18 07:46:05,744: topic[/mavros/battery] adding connection to [http://10.0.0.116:35943/], count 0
[rospy.internal][INFO] 2017-10-18 07:46:06,079: topic[/mavros/mission/waypoints] adding connection to [http://10.0.0.116:35943/], count 0
[rospy.internal][INFO] 2017-10-18 07:46:06,155: topic[/mavros/rc/override] adding connection to [/mavros], count 0
[rospy.internal][INFO] 2017-10-18 07:46:06,175: topic[/state_command] adding connection to [http://10.0.0.116:34779/], count 4
[rospy.internal][INFO] 2017-10-18 07:46:06,319: topic[/exec_command] adding connection to [/exec], count 0
[rospy.core][INFO] 2017-10-18 07:46:20,525: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-10-18 07:46:20,726: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-18 07:46:20,728: topic[/mavros/rc/override] removing connection to /mavros
[rospy.internal][INFO] 2017-10-18 07:46:20,729: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][INFO] 2017-10-18 07:46:20,730: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][ERROR] 2017-10-18 07:46:20,731: Unable to initiate TCP/IP socket to 10.0.0.116:42912 (http://10.0.0.116:40658/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:46:20,732: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][INFO] 2017-10-18 07:46:20,738: topic[/state_command] removing connection to /state_driving_to_cone
[rospy.internal][INFO] 2017-10-18 07:46:20,755: topic[/exec_command] removing connection to /exec
[rospy.internal][ERROR] 2017-10-18 07:46:20,758: Unable to initiate TCP/IP socket to 10.0.0.116:39276 (http://10.0.0.116:37475/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-18 07:46:20,761: Unable to initiate TCP/IP socket to 10.0.0.116:42387 (http://10.0.0.116:34779/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-18 07:46:20,759: Unable to initiate TCP/IP socket to 10.0.0.116:36615 (http://10.0.0.116:43499/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:46:20,763: topic[/mavros/mission/waypoints] removing connection to http://10.0.0.116:35943/
[rospy.internal][INFO] 2017-10-18 07:46:20,765: topic[/mavros/state] removing connection to http://10.0.0.116:35943/
[rospy.internal][WARNING] 2017-10-18 07:46:20,766: Unknown error initiating TCP/IP socket to 10.0.0.116:35884 (http://10.0.0.116:35943/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2017-10-18 07:46:20,767: topic[/mavlink/from] removing connection to http://10.0.0.116:35943/
[rospy.internal][INFO] 2017-10-18 07:46:20,771: topic[/mavros/local_position/pose] removing connection to http://10.0.0.116:35943/
[rospy.internal][WARNING] 2017-10-18 07:46:20,771: Unknown error initiating TCP/IP socket to 10.0.0.116:35884 (http://10.0.0.116:35943/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][ERROR] 2017-10-18 07:46:20,772: Unable to initiate TCP/IP socket to 10.0.0.116:33101 (http://10.0.0.116:33171/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2017-10-18 07:46:20,788: Unknown error initiating TCP/IP socket to 10.0.0.116:35884 (http://10.0.0.116:35943/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2017-10-18 07:46:20,786: topic[/mavros/battery] removing connection to http://10.0.0.116:35943/
[rospy.internal][INFO] 2017-10-18 07:46:20,789: topic[/state_command] removing connection to http://10.0.0.116:33171/
[rospy.internal][INFO] 2017-10-18 07:46:20,790: topic[/state_command] removing connection to http://10.0.0.116:40658/
[rospy.internal][INFO] 2017-10-18 07:46:20,793: topic[/state_command] removing connection to http://10.0.0.116:37475/
[rospy.internal][INFO] 2017-10-18 07:46:20,793: topic[/state_command] removing connection to http://10.0.0.116:43499/
[rospy.internal][INFO] 2017-10-18 07:46:20,794: topic[/state_command] removing connection to http://10.0.0.116:34779/
[rospy.internal][INFO] 2017-10-18 07:46:20,795: topic[/mavros/setpoint_raw/target_local] removing connection to http://10.0.0.116:35943/
[rospy.impl.masterslave][INFO] 2017-10-18 07:46:20,796: signal-2
[rospy.core][INFO] 2017-10-18 07:46:21,163: signal_shutdown [atexit]
