[rospy.client][INFO] 2017-10-18 07:49:35,703: init_node, name[/state_driving_away], pid[2287]
[xmlrpc][INFO] 2017-10-18 07:49:35,705: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-10-18 07:49:35,707: Started XML-RPC server [http://10.0.0.116:45498/]
[rospy.impl.masterslave][INFO] 2017-10-18 07:49:35,707: _ready: http://10.0.0.116:45498/
[rospy.registration][INFO] 2017-10-18 07:49:35,709: Registering with master node http://10.0.0.116:11311
[xmlrpc][INFO] 2017-10-18 07:49:35,710: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2017-10-18 07:49:35,716: ROS Slave URI: [http://10.0.0.116:45498/]
[rospy.init][INFO] 2017-10-18 07:49:35,717: registered with master
[rospy.rosout][INFO] 2017-10-18 07:49:35,717: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-18 07:49:35,742: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-18 07:49:35,753: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-18 07:49:35,891: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-18 07:49:35,954: topic[/state_command] adding connection to [http://10.0.0.116:36742/], count 0
[rospy.internal][INFO] 2017-10-18 07:49:35,968: topic[/state_command] adding connection to [http://10.0.0.116:45498/], count 1
[rospy.internal][INFO] 2017-10-18 07:49:35,971: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 0
[rospy.internal][INFO] 2017-10-18 07:49:35,994: topic[/state_command] adding connection to [/state_driving_away], count 1
[rospy.internal][INFO] 2017-10-18 07:49:36,139: topic[/state_command] adding connection to [http://10.0.0.116:35786/], count 2
[rospy.internal][INFO] 2017-10-18 07:49:36,190: topic[/state_command] adding connection to [/state_follow_waypoint], count 2
[rospy.internal][INFO] 2017-10-18 07:49:37,239: topic[/state_command] adding connection to [/state_driving_to_cone], count 3
[rospy.internal][INFO] 2017-10-18 07:49:37,241: topic[/state_command] adding connection to [http://10.0.0.116:41132/], count 3
[rospy.internal][INFO] 2017-10-18 07:49:37,644: topic[/mavros/setpoint_raw/target_local] adding connection to [http://10.0.0.116:45491/], count 0
[rospy.internal][INFO] 2017-10-18 07:49:37,672: topic[/mavros/state] adding connection to [http://10.0.0.116:45491/], count 0
[rospy.internal][INFO] 2017-10-18 07:49:37,701: topic[/mavlink/from] adding connection to [http://10.0.0.116:45491/], count 0
[rospy.internal][INFO] 2017-10-18 07:49:37,706: topic[/mavros/battery] adding connection to [http://10.0.0.116:45491/], count 0
[rospy.internal][INFO] 2017-10-18 07:49:37,711: topic[/mavros/local_position/pose] adding connection to [http://10.0.0.116:45491/], count 0
[rospy.internal][INFO] 2017-10-18 07:49:38,059: topic[/mavros/rc/override] adding connection to [/mavros], count 0
[rospy.internal][INFO] 2017-10-18 07:49:38,062: topic[/mavros/mission/waypoints] adding connection to [http://10.0.0.116:45491/], count 0
[rospy.internal][INFO] 2017-10-18 07:49:38,459: topic[/state_command] adding connection to [http://10.0.0.116:36232/], count 4
[rospy.internal][INFO] 2017-10-18 07:49:38,480: topic[/exec_command] adding connection to [/exec], count 0
[rospy.core][INFO] 2017-10-18 07:49:47,894: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-10-18 07:49:48,180: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-18 07:49:48,181: topic[/mavros/rc/override] removing connection to /mavros
[rospy.internal][INFO] 2017-10-18 07:49:48,185: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][INFO] 2017-10-18 07:49:48,185: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][ERROR] 2017-10-18 07:49:48,188: Unable to initiate TCP/IP socket to 10.0.0.116:42371 (http://10.0.0.116:45498/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:49:48,191: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][INFO] 2017-10-18 07:49:48,195: topic[/state_command] removing connection to /state_driving_to_cone
[rospy.internal][INFO] 2017-10-18 07:49:48,195: topic[/exec_command] removing connection to /exec
[rospy.internal][INFO] 2017-10-18 07:49:48,198: topic[/mavros/mission/waypoints] removing connection to http://10.0.0.116:45491/
[rospy.internal][WARNING] 2017-10-18 07:49:48,199: Unknown error initiating TCP/IP socket to 10.0.0.116:56049 (http://10.0.0.116:45491/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2017-10-18 07:49:48,203: topic[/mavros/state] removing connection to http://10.0.0.116:45491/
[rospy.internal][INFO] 2017-10-18 07:49:48,204: topic[/mavlink/from] removing connection to http://10.0.0.116:45491/
[rospy.internal][WARNING] 2017-10-18 07:49:48,207: Unknown error initiating TCP/IP socket to 10.0.0.116:56049 (http://10.0.0.116:45491/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2017-10-18 07:49:48,208: topic[/mavros/local_position/pose] removing connection to http://10.0.0.116:45491/
[rospy.internal][INFO] 2017-10-18 07:49:48,210: topic[/mavros/battery] removing connection to http://10.0.0.116:45491/
[rospy.internal][WARNING] 2017-10-18 07:49:48,211: Unknown error initiating TCP/IP socket to 10.0.0.116:56049 (http://10.0.0.116:45491/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2017-10-18 07:49:48,211: topic[/state_command] removing connection to http://10.0.0.116:36742/
[rospy.internal][INFO] 2017-10-18 07:49:48,213: topic[/state_command] removing connection to http://10.0.0.116:45498/
[rospy.internal][INFO] 2017-10-18 07:49:48,214: topic[/state_command] removing connection to http://10.0.0.116:35786/
[rospy.internal][INFO] 2017-10-18 07:49:48,215: topic[/state_command] removing connection to http://10.0.0.116:41132/
[rospy.internal][INFO] 2017-10-18 07:49:48,219: topic[/state_command] removing connection to http://10.0.0.116:36232/
[rospy.internal][INFO] 2017-10-18 07:49:48,225: topic[/mavros/setpoint_raw/target_local] removing connection to http://10.0.0.116:45491/
[rospy.impl.masterslave][INFO] 2017-10-18 07:49:48,226: signal-2
[rospy.internal][WARNING] 2017-10-18 07:49:48,229: Unknown error initiating TCP/IP socket to 10.0.0.116:56049 (http://10.0.0.116:45491/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.core][INFO] 2017-10-18 07:49:48,542: signal_shutdown [atexit]
