[rospy.client][INFO] 2017-10-18 07:48:29,885: init_node, name[/state_driving_away], pid[30834]
[xmlrpc][INFO] 2017-10-18 07:48:29,887: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2017-10-18 07:48:29,888: ROS Slave URI: [http://10.0.0.116:41980/]
[xmlrpc][INFO] 2017-10-18 07:48:29,889: Started XML-RPC server [http://10.0.0.116:41980/]
[rospy.impl.masterslave][INFO] 2017-10-18 07:48:29,890: _ready: http://10.0.0.116:41980/
[xmlrpc][INFO] 2017-10-18 07:48:29,890: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-10-18 07:48:29,892: Registering with master node http://10.0.0.116:11311
[rospy.init][INFO] 2017-10-18 07:48:29,991: registered with master
[rospy.rosout][INFO] 2017-10-18 07:48:29,992: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-18 07:48:30,008: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-18 07:48:30,023: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-18 07:48:30,172: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 0
[rospy.internal][INFO] 2017-10-18 07:48:30,179: topic[/state_command] adding connection to [/state_driving_to_cone], count 1
[rospy.internal][INFO] 2017-10-18 07:48:30,183: topic[/state_command] adding connection to [/state_follow_waypoint], count 2
[rospy.internal][INFO] 2017-10-18 07:48:30,229: topic[/state_command] adding connection to [http://10.0.0.116:43297/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:30,232: topic[/state_command] adding connection to [http://10.0.0.116:35502/], count 1
[rospy.internal][INFO] 2017-10-18 07:48:30,241: topic[/state_command] adding connection to [http://10.0.0.116:39812/], count 2
[rospy.internal][INFO] 2017-10-18 07:48:30,244: topic[/state_command] adding connection to [http://10.0.0.116:41980/], count 2
[rospy.internal][INFO] 2017-10-18 07:48:30,268: topic[/state_command] adding connection to [/state_driving_away], count 3
[rospy.internal][INFO] 2017-10-18 07:48:30,350: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-18 07:48:31,371: topic[/mavros/local_position/pose] adding connection to [http://10.0.0.116:37215/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:31,429: topic[/mavros/setpoint_raw/target_local] adding connection to [http://10.0.0.116:37215/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:31,489: topic[/mavros/battery] adding connection to [http://10.0.0.116:37215/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:31,493: topic[/mavros/state] adding connection to [http://10.0.0.116:37215/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:31,615: topic[/mavlink/from] adding connection to [http://10.0.0.116:37215/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:31,974: topic[/state_command] adding connection to [http://10.0.0.116:38610/], count 4
[rospy.internal][INFO] 2017-10-18 07:48:31,989: topic[/exec_command] adding connection to [/exec], count 0
[rospy.internal][INFO] 2017-10-18 07:48:32,013: topic[/mavros/mission/waypoints] adding connection to [http://10.0.0.116:37215/], count 0
[rospy.internal][INFO] 2017-10-18 07:48:32,147: topic[/mavros/rc/override] adding connection to [/mavros], count 0
[rosout][INFO] 2017-10-18 07:48:43,466: /state_driving_away MsgId 46 detected. WP item # 7936
[rospy.core][INFO] 2017-10-18 07:48:59,843: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2017-10-18 07:49:00,067: Unable to initiate TCP/IP socket to 10.0.0.116:44721 (http://10.0.0.116:39812/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:49:00,160: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-18 07:49:00,188: topic[/mavros/rc/override] removing connection to /mavros
[rospy.internal][INFO] 2017-10-18 07:49:00,189: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][INFO] 2017-10-18 07:49:00,196: topic[/state_command] removing connection to /state_driving_to_cone
[rospy.internal][INFO] 2017-10-18 07:49:00,198: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][ERROR] 2017-10-18 07:49:00,199: Unable to initiate TCP/IP socket to 10.0.0.116:39697 (http://10.0.0.116:35502/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-18 07:49:00,203: Unable to initiate TCP/IP socket to 10.0.0.116:44738 (http://10.0.0.116:41980/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:49:00,207: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][INFO] 2017-10-18 07:49:00,208: topic[/exec_command] removing connection to /exec
[rospy.internal][INFO] 2017-10-18 07:49:00,217: topic[/mavros/mission/waypoints] removing connection to http://10.0.0.116:37215/
[rospy.internal][INFO] 2017-10-18 07:49:00,220: topic[/mavros/state] removing connection to http://10.0.0.116:37215/
[rospy.internal][INFO] 2017-10-18 07:49:00,226: topic[/mavlink/from] removing connection to http://10.0.0.116:37215/
[rospy.internal][INFO] 2017-10-18 07:49:00,229: topic[/mavros/local_position/pose] removing connection to http://10.0.0.116:37215/
[rospy.internal][INFO] 2017-10-18 07:49:00,230: topic[/mavros/battery] removing connection to http://10.0.0.116:37215/
[rospy.internal][WARNING] 2017-10-18 07:49:00,232: Unknown error initiating TCP/IP socket to 10.0.0.116:47667 (http://10.0.0.116:37215/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2017-10-18 07:49:00,234: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2017-10-18 07:49:00,234: topic[/state_command] removing connection to http://10.0.0.116:43297/
[rospy.internal][INFO] 2017-10-18 07:49:00,235: topic[/state_command] removing connection to http://10.0.0.116:35502/
[rospy.internal][INFO] 2017-10-18 07:49:00,235: topic[/state_command] removing connection to http://10.0.0.116:39812/
[rospy.internal][INFO] 2017-10-18 07:49:00,236: topic[/state_command] removing connection to http://10.0.0.116:41980/
[rospy.internal][INFO] 2017-10-18 07:49:00,236: topic[/state_command] removing connection to http://10.0.0.116:38610/
[rospy.internal][INFO] 2017-10-18 07:49:00,237: topic[/mavros/setpoint_raw/target_local] removing connection to http://10.0.0.116:37215/
[rospy.impl.masterslave][INFO] 2017-10-18 07:49:00,249: signal-2
[rospy.core][INFO] 2017-10-18 07:49:00,467: signal_shutdown [atexit]
