[rospy.client][INFO] 2017-10-18 07:32:49,634: init_node, name[/state_driving_to_cone], pid[5229]
[xmlrpc][INFO] 2017-10-18 07:32:49,636: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2017-10-18 07:32:49,639: ROS Slave URI: [http://10.0.0.116:42801/]
[xmlrpc][INFO] 2017-10-18 07:32:49,639: Started XML-RPC server [http://10.0.0.116:42801/]
[rospy.impl.masterslave][INFO] 2017-10-18 07:32:49,640: _ready: http://10.0.0.116:42801/
[xmlrpc][INFO] 2017-10-18 07:32:49,640: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-10-18 07:32:49,642: Registering with master node http://10.0.0.116:11311
[rospy.init][INFO] 2017-10-18 07:32:49,739: registered with master
[rospy.rosout][INFO] 2017-10-18 07:32:49,740: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-18 07:32:49,752: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-18 07:32:49,762: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-18 07:32:49,872: topic[/state_command] adding connection to [http://10.0.0.116:42801/], count 0
[rospy.internal][INFO] 2017-10-18 07:32:49,875: topic[/state_command] adding connection to [http://10.0.0.116:34176/], count 1
[rospy.internal][INFO] 2017-10-18 07:32:49,879: topic[/state_command] adding connection to [http://10.0.0.116:33147/], count 2
[rospy.internal][INFO] 2017-10-18 07:32:49,894: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 0
[rospy.internal][INFO] 2017-10-18 07:32:49,900: topic[/state_command] adding connection to [/state_driving_to_cone], count 1
[rospy.internal][INFO] 2017-10-18 07:32:49,909: topic[/state_command] adding connection to [/state_driving_away], count 2
[rospy.internal][INFO] 2017-10-18 07:32:49,997: topic[/state_command] adding connection to [http://10.0.0.116:41071/], count 3
[rospy.internal][INFO] 2017-10-18 07:32:50,007: topic[/state_command] adding connection to [/state_follow_waypoint], count 3
[rospy.internal][INFO] 2017-10-18 07:32:50,018: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-18 07:32:50,984: topic[/mavros/local_position/pose] adding connection to [http://10.0.0.116:42365/], count 0
[rospy.internal][INFO] 2017-10-18 07:32:51,079: topic[/mavros/setpoint_raw/target_local] adding connection to [http://10.0.0.116:42365/], count 0
[rospy.internal][INFO] 2017-10-18 07:32:51,124: topic[/mavros/battery] adding connection to [http://10.0.0.116:42365/], count 0
[rospy.internal][INFO] 2017-10-18 07:32:51,127: topic[/mavlink/from] adding connection to [http://10.0.0.116:42365/], count 0
[rospy.internal][INFO] 2017-10-18 07:32:51,130: topic[/mavros/state] adding connection to [http://10.0.0.116:42365/], count 0
[rospy.internal][INFO] 2017-10-18 07:32:51,310: topic[/mavros/mission/waypoints] adding connection to [http://10.0.0.116:42365/], count 0
[rospy.internal][INFO] 2017-10-18 07:32:51,348: topic[/exec_command] adding connection to [/exec], count 0
[rospy.internal][INFO] 2017-10-18 07:32:51,429: topic[/state_command] adding connection to [http://10.0.0.116:38599/], count 4
[rospy.internal][INFO] 2017-10-18 07:32:51,481: topic[/mavros/rc/override] adding connection to [/mavros], count 0
[rospy.core][INFO] 2017-10-18 07:33:29,895: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2017-10-18 07:33:30,089: Unable to initiate TCP/IP socket to 10.0.0.116:36384 (http://10.0.0.116:34176/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:33:30,107: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-18 07:33:30,109: topic[/mavros/rc/override] removing connection to /mavros
[rospy.internal][ERROR] 2017-10-18 07:33:30,110: Unable to initiate TCP/IP socket to 10.0.0.116:38431 (http://10.0.0.116:33147/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:33:30,111: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][INFO] 2017-10-18 07:33:30,112: topic[/state_command] removing connection to /state_driving_to_cone
[rospy.internal][INFO] 2017-10-18 07:33:30,115: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][ERROR] 2017-10-18 07:33:30,118: Unable to initiate TCP/IP socket to 10.0.0.116:38642 (http://10.0.0.116:42801/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:33:30,119: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][INFO] 2017-10-18 07:33:30,127: topic[/exec_command] removing connection to /exec
[rospy.internal][INFO] 2017-10-18 07:33:30,133: topic[/mavros/mission/waypoints] removing connection to http://10.0.0.116:42365/
[rospy.internal][INFO] 2017-10-18 07:33:30,136: topic[/mavros/state] removing connection to http://10.0.0.116:42365/
[rospy.internal][WARNING] 2017-10-18 07:33:30,138: Unknown error initiating TCP/IP socket to 10.0.0.116:36402 (http://10.0.0.116:42365/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2017-10-18 07:33:30,139: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2017-10-18 07:33:30,140: topic[/mavlink/from] removing connection to http://10.0.0.116:42365/
[rospy.internal][INFO] 2017-10-18 07:33:30,141: topic[/mavros/local_position/pose] removing connection to http://10.0.0.116:42365/
[rospy.internal][INFO] 2017-10-18 07:33:30,142: topic[/mavros/battery] removing connection to http://10.0.0.116:42365/
[rospy.internal][INFO] 2017-10-18 07:33:30,143: topic[/state_command] removing connection to http://10.0.0.116:42801/
[rospy.internal][INFO] 2017-10-18 07:33:30,143: topic[/state_command] removing connection to http://10.0.0.116:34176/
[rospy.internal][INFO] 2017-10-18 07:33:30,144: topic[/state_command] removing connection to http://10.0.0.116:33147/
[rospy.internal][INFO] 2017-10-18 07:33:30,148: topic[/state_command] removing connection to http://10.0.0.116:41071/
[rospy.internal][INFO] 2017-10-18 07:33:30,148: topic[/state_command] removing connection to http://10.0.0.116:38599/
[rospy.internal][INFO] 2017-10-18 07:33:30,150: topic[/mavros/setpoint_raw/target_local] removing connection to http://10.0.0.116:42365/
[rospy.internal][WARNING] 2017-10-18 07:33:30,155: Unknown error initiating TCP/IP socket to 10.0.0.116:36402 (http://10.0.0.116:42365/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.impl.masterslave][INFO] 2017-10-18 07:33:30,156: signal-2
[rospy.core][INFO] 2017-10-18 07:33:30,268: signal_shutdown [atexit]
