[rospy.client][INFO] 2017-10-02 12:54:41,305: init_node, name[/state_driving_away], pid[6423]
[xmlrpc][INFO] 2017-10-02 12:54:41,316: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2017-10-02 12:54:41,318: ROS Slave URI: [http://10.0.0.116:37656/]
[xmlrpc][INFO] 2017-10-02 12:54:41,317: Started XML-RPC server [http://10.0.0.116:37656/]
[rospy.impl.masterslave][INFO] 2017-10-02 12:54:41,319: _ready: http://10.0.0.116:37656/
[xmlrpc][INFO] 2017-10-02 12:54:41,319: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-10-02 12:54:41,336: Registering with master node http://10.0.0.116:11311
[rospy.init][INFO] 2017-10-02 12:54:41,418: registered with master
[rospy.rosout][INFO] 2017-10-02 12:54:41,419: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-02 12:54:41,427: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-02 12:54:41,448: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-02 12:54:41,668: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-02 12:54:41,713: topic[/state_command] adding connection to [http://10.0.0.116:37656/], count 0
[rospy.internal][INFO] 2017-10-02 12:54:41,722: topic[/state_command] adding connection to [http://10.0.0.116:44619/], count 1
[rospy.internal][INFO] 2017-10-02 12:54:41,751: topic[/state_command] adding connection to [/state_driving_away], count 0
[rospy.internal][INFO] 2017-10-02 12:54:41,813: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 1
[rospy.internal][INFO] 2017-10-02 12:54:42,249: topic[/state_command] adding connection to [/state_follow_waypoint], count 2
[rospy.internal][INFO] 2017-10-02 12:54:42,288: topic[/state_command] adding connection to [http://10.0.0.116:45876/], count 2
[rospy.core][INFO] 2017-10-02 12:54:42,413: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-10-02 12:54:42,457: topic[/state_command] adding connection to [http://10.0.0.116:44767/], count 3
[rospy.internal][ERROR] 2017-10-02 12:54:42,464: Unable to initiate TCP/IP socket to 10.0.0.116:35748 (http://10.0.0.116:44767/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-02 12:54:42,465: unable to create subscriber transport: remote error reported: node shutting down.  Will try again in 0.5s
[rospy.internal][INFO] 2017-10-02 12:54:42,556: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-02 12:54:42,557: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][INFO] 2017-10-02 12:54:42,559: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][ERROR] 2017-10-02 12:54:42,560: Unable to initiate TCP/IP socket to 10.0.0.116:41536 (http://10.0.0.116:37656/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-02 12:54:42,561: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][INFO] 2017-10-02 12:54:42,563: topic[/state_command] removing connection to http://10.0.0.116:37656/
[rospy.internal][INFO] 2017-10-02 12:54:42,564: topic[/state_command] removing connection to http://10.0.0.116:44619/
[rospy.internal][ERROR] 2017-10-02 12:54:42,567: Unable to initiate TCP/IP socket to 10.0.0.116:36310 (http://10.0.0.116:45876/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-02 12:54:42,566: topic[/state_command] removing connection to http://10.0.0.116:45876/
[rospy.internal][INFO] 2017-10-02 12:54:42,568: topic[/state_command] removing connection to http://10.0.0.116:44767/
[rospy.impl.masterslave][INFO] 2017-10-02 12:54:42,568: signal-2
[rospy.core][INFO] 2017-10-02 12:54:43,085: signal_shutdown [atexit]
