[rospy.client][INFO] 2017-10-02 12:54:42,096: init_node, name[/state_follow_waypoint], pid[6398]
[xmlrpc][INFO] 2017-10-02 12:54:42,098: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-10-02 12:54:42,099: Started XML-RPC server [http://10.0.0.116:45876/]
[rospy.impl.masterslave][INFO] 2017-10-02 12:54:42,099: _ready: http://10.0.0.116:45876/
[xmlrpc][INFO] 2017-10-02 12:54:42,102: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-10-02 12:54:42,101: Registering with master node http://10.0.0.116:11311
[rospy.init][INFO] 2017-10-02 12:54:42,107: ROS Slave URI: [http://10.0.0.116:45876/]
[rospy.init][INFO] 2017-10-02 12:54:42,107: registered with master
[rospy.rosout][INFO] 2017-10-02 12:54:42,108: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-02 12:54:42,119: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-02 12:54:42,133: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-02 12:54:42,232: topic[/state_command] adding connection to [http://10.0.0.116:37656/], count 0
[rospy.internal][INFO] 2017-10-02 12:54:42,244: topic[/state_command] adding connection to [http://10.0.0.116:45876/], count 1
[rospy.internal][INFO] 2017-10-02 12:54:42,245: topic[/state_command] adding connection to [http://10.0.0.116:44619/], count 2
[rospy.internal][INFO] 2017-10-02 12:54:42,260: topic[/state_command] adding connection to [/state_follow_waypoint], count 0
[rospy.internal][INFO] 2017-10-02 12:54:42,293: topic[/state_command] adding connection to [/state_driving_away], count 1
[rospy.internal][INFO] 2017-10-02 12:54:42,312: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 2
[rospy.internal][INFO] 2017-10-02 12:54:42,388: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2017-10-02 12:54:42,421: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-10-02 12:54:42,476: topic[/state_command] adding connection to [http://10.0.0.116:44767/], count 3
[rospy.internal][ERROR] 2017-10-02 12:54:42,478: Unable to initiate TCP/IP socket to 10.0.0.116:35748 (http://10.0.0.116:44767/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-02 12:54:42,479: unable to create subscriber transport: remote error reported: node shutting down.  Will try again in 0.5s
[rospy.internal][ERROR] 2017-10-02 12:54:42,563: Unable to initiate TCP/IP socket to 10.0.0.116:41536 (http://10.0.0.116:37656/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-02 12:54:42,586: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][ERROR] 2017-10-02 12:54:42,603: Unable to initiate TCP/IP socket to 10.0.0.116:34017 (http://10.0.0.116:44619/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-02 12:54:42,613: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-02 12:54:42,614: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][INFO] 2017-10-02 12:54:42,615: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][INFO] 2017-10-02 12:54:42,617: topic[/state_command] removing connection to http://10.0.0.116:37656/
[rospy.internal][INFO] 2017-10-02 12:54:42,618: topic[/state_command] removing connection to http://10.0.0.116:45876/
[rospy.internal][INFO] 2017-10-02 12:54:42,618: topic[/state_command] removing connection to http://10.0.0.116:44619/
[rospy.internal][ERROR] 2017-10-02 12:54:42,619: Unable to initiate TCP/IP socket to 10.0.0.116:36310 (http://10.0.0.116:45876/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-02 12:54:42,620: topic[/state_command] removing connection to http://10.0.0.116:44767/
[rospy.impl.masterslave][INFO] 2017-10-02 12:54:42,621: signal-2
[rospy.core][INFO] 2017-10-02 12:54:43,542: signal_shutdown [atexit]
