[rospy.client][INFO] 2017-10-18 07:39:26,803: init_node, name[/exec], pid[13596]
[xmlrpc][INFO] 2017-10-18 07:39:26,804: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2017-10-18 07:39:26,820: ROS Slave URI: [http://10.0.0.116:38160/]
[xmlrpc][INFO] 2017-10-18 07:39:26,820: Started XML-RPC server [http://10.0.0.116:38160/]
[rospy.impl.masterslave][INFO] 2017-10-18 07:39:26,821: _ready: http://10.0.0.116:38160/
[xmlrpc][INFO] 2017-10-18 07:39:26,822: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-10-18 07:39:26,824: Registering with master node http://10.0.0.116:11311
[rospy.registration][INFO] 2017-10-18 07:39:26,824: Registering publisher topic [/play] type [std_msgs/String] with master
[rospy.init][INFO] 2017-10-18 07:39:26,920: registered with master
[rospy.rosout][INFO] 2017-10-18 07:39:26,921: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-18 07:39:26,932: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-18 07:39:26,939: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-18 07:39:27,154: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-18 07:39:28,444: topic[/play] adding connection to [/chatty], count 0
[rospy.internal][INFO] 2017-10-18 07:39:28,921: topic[/mavros/local_position/pose] adding connection to [http://10.0.0.116:35438/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:28,952: topic[/mavros/setpoint_raw/target_local] adding connection to [http://10.0.0.116:35438/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:28,972: topic[/mavlink/from] adding connection to [http://10.0.0.116:35438/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:28,977: topic[/mavros/battery] adding connection to [http://10.0.0.116:35438/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:28,982: topic[/mavros/state] adding connection to [http://10.0.0.116:35438/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,267: topic[/mavros/mission/waypoints] adding connection to [http://10.0.0.116:35438/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,306: topic[/mavros/rc/override] adding connection to [/mavros], count 0
[rosout][INFO] 2017-10-18 07:39:29,375: Exec is starting
[rospy.internal][INFO] 2017-10-18 07:39:29,383: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,390: topic[/exec_command] adding connection to [http://10.0.0.116:42879/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,393: topic[/exec_command] adding connection to [http://10.0.0.116:37775/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,404: topic[/exec_command] adding connection to [http://10.0.0.116:46200/], count 2
[rospy.internal][INFO] 2017-10-18 07:39:29,429: topic[/exec_command] adding connection to [http://10.0.0.116:45821/], count 3
[rospy.internal][INFO] 2017-10-18 07:39:29,450: topic[/exec_command] adding connection to [http://10.0.0.116:38160/], count 4
[rospy.internal][INFO] 2017-10-18 07:39:29,470: topic[/state_command] adding connection to [/state_driving_to_cone], count 1
[rospy.internal][INFO] 2017-10-18 07:39:29,477: topic[/exec_command] adding connection to [/exec], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,488: topic[/state_command] adding connection to [/state_follow_waypoint], count 2
[rospy.internal][INFO] 2017-10-18 07:39:29,494: topic[/state_command] adding connection to [/state_driving_away], count 3
[rosout][INFO] 2017-10-18 07:39:33,138: /exec MsgId 46 detected. WP item # 185
[rosout][INFO] 2017-10-18 07:39:39,376: New parameters received
[rosout][INFO] 2017-10-18 07:39:40,376: New parameters received
[rosout][INFO] 2017-10-18 07:39:41,376: New parameters received
[rosout][INFO] 2017-10-18 07:39:42,376: New parameters received
[rosout][INFO] 2017-10-18 07:39:43,376: New parameters received
[rosout][INFO] 2017-10-18 07:39:44,376: New parameters received
[rosout][INFO] 2017-10-18 07:39:45,376: New parameters received
[rosout][INFO] 2017-10-18 07:39:46,376: New parameters received
[rosout][INFO] 2017-10-18 07:39:47,376: New parameters received
[rosout][INFO] 2017-10-18 07:39:48,377: New parameters received
[rosout][INFO] 2017-10-18 07:39:49,376: New parameters received
[rosout][INFO] 2017-10-18 07:40:05,376: New parameters received
[rospy.core][INFO] 2017-10-18 07:41:28,186: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-10-18 07:41:28,199: topic[/play] removing connection to /chatty
[rospy.internal][ERROR] 2017-10-18 07:41:28,405: Unable to initiate TCP/IP socket to 10.0.0.116:38107 (http://10.0.0.116:45821/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-18 07:41:28,464: Unable to initiate TCP/IP socket to 10.0.0.116:44934 (http://10.0.0.116:37775/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-18 07:41:28,472: Unable to initiate TCP/IP socket to 10.0.0.116:38279 (http://10.0.0.116:42879/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:41:28,485: topic[/mavros/rc/override] removing connection to /mavros
[rospy.internal][INFO] 2017-10-18 07:41:28,487: topic[/exec_command] removing connection to /exec
[rospy.internal][ERROR] 2017-10-18 07:41:28,489: Unable to initiate TCP/IP socket to 10.0.0.116:39504 (http://10.0.0.116:38160/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:41:28,490: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-18 07:41:28,492: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][INFO] 2017-10-18 07:41:28,494: topic[/state_command] removing connection to /state_driving_to_cone
[rospy.internal][INFO] 2017-10-18 07:41:28,495: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][INFO] 2017-10-18 07:41:28,497: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][INFO] 2017-10-18 07:41:28,498: topic[/mavros/mission/waypoints] removing connection to http://10.0.0.116:35438/
[rospy.internal][ERROR] 2017-10-18 07:41:28,499: Unable to initiate TCP/IP socket to 10.0.0.116:42685 (http://10.0.0.116:46200/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:41:28,501: topic[/exec_command] removing connection to http://10.0.0.116:42879/
[rospy.internal][INFO] 2017-10-18 07:41:28,501: topic[/exec_command] removing connection to http://10.0.0.116:37775/
[rospy.internal][INFO] 2017-10-18 07:41:28,502: topic[/exec_command] removing connection to http://10.0.0.116:46200/
[rospy.internal][INFO] 2017-10-18 07:41:28,503: topic[/exec_command] removing connection to http://10.0.0.116:45821/
[rospy.internal][INFO] 2017-10-18 07:41:28,509: topic[/exec_command] removing connection to http://10.0.0.116:38160/
[rospy.internal][INFO] 2017-10-18 07:41:28,511: topic[/mavros/state] removing connection to http://10.0.0.116:35438/
[rospy.internal][WARNING] 2017-10-18 07:41:28,513: Unknown error initiating TCP/IP socket to 10.0.0.116:45044 (http://10.0.0.116:35438/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2017-10-18 07:41:28,515: topic[/mavlink/from] removing connection to http://10.0.0.116:35438/
[rospy.internal][WARNING] 2017-10-18 07:41:28,516: Unknown error initiating TCP/IP socket to 10.0.0.116:45044 (http://10.0.0.116:35438/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2017-10-18 07:41:28,517: topic[/mavros/local_position/pose] removing connection to http://10.0.0.116:35438/
[rospy.internal][WARNING] 2017-10-18 07:41:28,519: Unknown error initiating TCP/IP socket to 10.0.0.116:45044 (http://10.0.0.116:35438/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2017-10-18 07:41:28,520: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2017-10-18 07:41:28,522: topic[/mavros/battery] removing connection to http://10.0.0.116:35438/
[rospy.internal][WARNING] 2017-10-18 07:41:28,522: Unknown error initiating TCP/IP socket to 10.0.0.116:45044 (http://10.0.0.116:35438/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][WARNING] 2017-10-18 07:41:28,524: Unknown error initiating TCP/IP socket to 10.0.0.116:45044 (http://10.0.0.116:35438/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2017-10-18 07:41:28,523: topic[/mavros/setpoint_raw/target_local] removing connection to http://10.0.0.116:35438/
[rospy.topics][ERROR] 2017-10-18 07:41:28,525: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2017-10-18 07:41:28,525: signal-2
[rospy.core][INFO] 2017-10-18 07:41:28,841: signal_shutdown [atexit]
