[rospy.client][INFO] 2017-10-18 07:39:27,828: init_node, name[/state_follow_waypoint], pid[13619]
[xmlrpc][INFO] 2017-10-18 07:39:27,830: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-10-18 07:39:27,831: Started XML-RPC server [http://10.0.0.116:37775/]
[rospy.impl.masterslave][INFO] 2017-10-18 07:39:27,833: _ready: http://10.0.0.116:37775/
[rospy.init][INFO] 2017-10-18 07:39:27,831: ROS Slave URI: [http://10.0.0.116:37775/]
[xmlrpc][INFO] 2017-10-18 07:39:27,836: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-10-18 07:39:27,835: Registering with master node http://10.0.0.116:11311
[rospy.init][INFO] 2017-10-18 07:39:27,936: registered with master
[rospy.rosout][INFO] 2017-10-18 07:39:27,937: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-18 07:39:27,965: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-18 07:39:27,982: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-18 07:39:28,152: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-18 07:39:28,168: topic[/state_command] adding connection to [http://10.0.0.116:37775/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:28,180: topic[/state_command] adding connection to [http://10.0.0.116:45821/], count 1
[rospy.internal][INFO] 2017-10-18 07:39:28,175: topic[/state_command] adding connection to [http://10.0.0.116:42879/], count 1
[rospy.internal][INFO] 2017-10-18 07:39:28,208: topic[/state_command] adding connection to [/state_follow_waypoint], count 0
[rospy.internal][INFO] 2017-10-18 07:39:28,211: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 1
[rospy.internal][INFO] 2017-10-18 07:39:28,213: topic[/state_command] adding connection to [/state_driving_away], count 2
[rospy.internal][INFO] 2017-10-18 07:39:28,415: topic[/state_command] adding connection to [http://10.0.0.116:46200/], count 3
[rospy.internal][INFO] 2017-10-18 07:39:28,422: topic[/state_command] adding connection to [/state_driving_to_cone], count 3
[rospy.internal][INFO] 2017-10-18 07:39:29,242: topic[/mavros/local_position/pose] adding connection to [http://10.0.0.116:35438/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,367: topic[/mavros/setpoint_raw/target_local] adding connection to [http://10.0.0.116:35438/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,404: topic[/exec_command] adding connection to [/exec], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,419: topic[/mavros/battery] adding connection to [http://10.0.0.116:35438/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,421: topic[/mavlink/from] adding connection to [http://10.0.0.116:35438/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,454: topic[/mavros/state] adding connection to [http://10.0.0.116:35438/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,466: topic[/state_command] adding connection to [http://10.0.0.116:38160/], count 4
[rospy.internal][INFO] 2017-10-18 07:39:29,605: topic[/mavros/mission/waypoints] adding connection to [http://10.0.0.116:35438/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,753: topic[/mavros/rc/override] adding connection to [/mavros], count 0
[rosout][INFO] 2017-10-18 07:39:33,137: /state_follow_waypoint MsgId 46 detected. WP item # 185
[rospy.core][INFO] 2017-10-18 07:41:28,189: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2017-10-18 07:41:28,399: Unable to initiate TCP/IP socket to 10.0.0.116:38107 (http://10.0.0.116:45821/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:41:28,436: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-18 07:41:28,438: topic[/mavros/rc/override] removing connection to /mavros
[rospy.internal][INFO] 2017-10-18 07:41:28,439: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][INFO] 2017-10-18 07:41:28,440: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][INFO] 2017-10-18 07:41:28,442: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][ERROR] 2017-10-18 07:41:28,444: Unable to initiate TCP/IP socket to 10.0.0.116:44934 (http://10.0.0.116:37775/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:41:28,457: topic[/state_command] removing connection to /state_driving_to_cone
[rospy.internal][ERROR] 2017-10-18 07:41:28,457: Unable to initiate TCP/IP socket to 10.0.0.116:38279 (http://10.0.0.116:42879/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:41:28,460: topic[/exec_command] removing connection to /exec
[rospy.internal][INFO] 2017-10-18 07:41:28,460: topic[/mavros/mission/waypoints] removing connection to http://10.0.0.116:35438/
[rospy.internal][INFO] 2017-10-18 07:41:28,462: topic[/mavros/state] removing connection to http://10.0.0.116:35438/
[rospy.internal][INFO] 2017-10-18 07:41:28,463: topic[/mavlink/from] removing connection to http://10.0.0.116:35438/
[rospy.internal][INFO] 2017-10-18 07:41:28,466: topic[/mavros/local_position/pose] removing connection to http://10.0.0.116:35438/
[rospy.internal][INFO] 2017-10-18 07:41:28,467: topic[/mavros/battery] removing connection to http://10.0.0.116:35438/
[rospy.internal][INFO] 2017-10-18 07:41:28,468: topic[/state_command] removing connection to http://10.0.0.116:37775/
[rospy.internal][INFO] 2017-10-18 07:41:28,468: topic[/state_command] removing connection to http://10.0.0.116:45821/
[rospy.internal][INFO] 2017-10-18 07:41:28,471: topic[/state_command] removing connection to http://10.0.0.116:42879/
[rospy.internal][INFO] 2017-10-18 07:41:28,472: topic[/state_command] removing connection to http://10.0.0.116:46200/
[rospy.internal][INFO] 2017-10-18 07:41:28,472: topic[/state_command] removing connection to http://10.0.0.116:38160/
[rospy.internal][INFO] 2017-10-18 07:41:28,474: topic[/mavros/setpoint_raw/target_local] removing connection to http://10.0.0.116:35438/
[rospy.impl.masterslave][INFO] 2017-10-18 07:41:28,485: signal-2
[rospy.core][INFO] 2017-10-18 07:41:28,813: signal_shutdown [atexit]
