[rospy.client][INFO] 2017-10-18 07:39:27,101: init_node, name[/state_driving_away], pid[13632]
[xmlrpc][INFO] 2017-10-18 07:39:27,107: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2017-10-18 07:39:27,109: ROS Slave URI: [http://10.0.0.116:45821/]
[xmlrpc][INFO] 2017-10-18 07:39:27,109: Started XML-RPC server [http://10.0.0.116:45821/]
[rospy.impl.masterslave][INFO] 2017-10-18 07:39:27,110: _ready: http://10.0.0.116:45821/
[xmlrpc][INFO] 2017-10-18 07:39:27,110: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-10-18 07:39:27,112: Registering with master node http://10.0.0.116:11311
[rospy.init][INFO] 2017-10-18 07:39:27,209: registered with master
[rospy.rosout][INFO] 2017-10-18 07:39:27,210: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-18 07:39:27,227: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-18 07:39:27,242: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-18 07:39:27,406: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 0
[rospy.internal][INFO] 2017-10-18 07:39:27,442: topic[/state_command] adding connection to [http://10.0.0.116:42879/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:27,455: topic[/state_command] adding connection to [http://10.0.0.116:45821/], count 1
[rospy.internal][INFO] 2017-10-18 07:39:27,478: topic[/state_command] adding connection to [/state_driving_away], count 1
[rospy.internal][INFO] 2017-10-18 07:39:27,513: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-18 07:39:28,201: topic[/state_command] adding connection to [/state_follow_waypoint], count 2
[rospy.internal][INFO] 2017-10-18 07:39:28,209: topic[/state_command] adding connection to [http://10.0.0.116:37775/], count 2
[rospy.internal][INFO] 2017-10-18 07:39:28,420: topic[/state_command] adding connection to [/state_driving_to_cone], count 3
[rospy.internal][INFO] 2017-10-18 07:39:28,436: topic[/state_command] adding connection to [http://10.0.0.116:46200/], count 3
[rospy.internal][INFO] 2017-10-18 07:39:29,127: topic[/mavros/local_position/pose] adding connection to [http://10.0.0.116:35438/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,303: topic[/mavlink/from] adding connection to [http://10.0.0.116:35438/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,308: topic[/mavros/setpoint_raw/target_local] adding connection to [http://10.0.0.116:35438/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,298: topic[/mavros/battery] adding connection to [http://10.0.0.116:35438/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,339: topic[/mavros/state] adding connection to [http://10.0.0.116:35438/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,449: topic[/exec_command] adding connection to [/exec], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,484: topic[/state_command] adding connection to [http://10.0.0.116:38160/], count 4
[rospy.internal][INFO] 2017-10-18 07:39:29,644: topic[/mavros/mission/waypoints] adding connection to [http://10.0.0.116:35438/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,753: topic[/mavros/rc/override] adding connection to [/mavros], count 0
[rosout][INFO] 2017-10-18 07:39:33,132: /state_driving_away MsgId 46 detected. WP item # 185
[rospy.core][INFO] 2017-10-18 07:41:28,168: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-10-18 07:41:28,391: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-18 07:41:28,392: topic[/mavros/rc/override] removing connection to /mavros
[rospy.internal][INFO] 2017-10-18 07:41:28,393: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][INFO] 2017-10-18 07:41:28,394: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][INFO] 2017-10-18 07:41:28,394: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][INFO] 2017-10-18 07:41:28,395: topic[/state_command] removing connection to /state_driving_to_cone
[rospy.internal][ERROR] 2017-10-18 07:41:28,402: Unable to initiate TCP/IP socket to 10.0.0.116:38107 (http://10.0.0.116:45821/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:41:28,404: topic[/exec_command] removing connection to /exec
[rospy.internal][INFO] 2017-10-18 07:41:28,407: topic[/mavros/mission/waypoints] removing connection to http://10.0.0.116:35438/
[rospy.internal][INFO] 2017-10-18 07:41:28,414: topic[/mavros/state] removing connection to http://10.0.0.116:35438/
[rospy.internal][INFO] 2017-10-18 07:41:28,414: topic[/mavlink/from] removing connection to http://10.0.0.116:35438/
[rospy.internal][WARNING] 2017-10-18 07:41:28,416: Unknown error initiating TCP/IP socket to 10.0.0.116:45044 (http://10.0.0.116:35438/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][WARNING] 2017-10-18 07:41:28,418: Unknown error initiating TCP/IP socket to 10.0.0.116:45044 (http://10.0.0.116:35438/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2017-10-18 07:41:28,415: topic[/mavros/local_position/pose] removing connection to http://10.0.0.116:35438/
[rospy.topics][ERROR] 2017-10-18 07:41:28,423: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2017-10-18 07:41:28,423: topic[/mavros/battery] removing connection to http://10.0.0.116:35438/
[rospy.internal][ERROR] 2017-10-18 07:41:28,426: Unable to initiate TCP/IP socket to 10.0.0.116:38279 (http://10.0.0.116:42879/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:41:28,427: topic[/state_command] removing connection to http://10.0.0.116:42879/
[rospy.topics][ERROR] 2017-10-18 07:41:28,427: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2017-10-18 07:41:28,428: topic[/state_command] removing connection to http://10.0.0.116:45821/
[rospy.internal][INFO] 2017-10-18 07:41:28,428: topic[/state_command] removing connection to http://10.0.0.116:37775/
[rospy.internal][INFO] 2017-10-18 07:41:28,429: topic[/state_command] removing connection to http://10.0.0.116:46200/
[rospy.internal][INFO] 2017-10-18 07:41:28,433: topic[/state_command] removing connection to http://10.0.0.116:38160/
[rospy.internal][INFO] 2017-10-18 07:41:28,434: topic[/mavros/setpoint_raw/target_local] removing connection to http://10.0.0.116:35438/
[rospy.impl.masterslave][INFO] 2017-10-18 07:41:28,435: signal-2
[rospy.internal][ERROR] 2017-10-18 07:41:28,436: Unable to initiate TCP/IP socket to 10.0.0.116:39504 (http://10.0.0.116:38160/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2017-10-18 07:41:28,803: signal_shutdown [atexit]
