[rospy.client][INFO] 2017-10-18 07:39:28,143: init_node, name[/state_driving_to_cone], pid[13626]
[xmlrpc][INFO] 2017-10-18 07:39:28,144: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-10-18 07:39:28,147: Started XML-RPC server [http://10.0.0.116:46200/]
[rospy.impl.masterslave][INFO] 2017-10-18 07:39:28,150: _ready: http://10.0.0.116:46200/
[rospy.init][INFO] 2017-10-18 07:39:28,152: ROS Slave URI: [http://10.0.0.116:46200/]
[rospy.registration][INFO] 2017-10-18 07:39:28,154: Registering with master node http://10.0.0.116:11311
[xmlrpc][INFO] 2017-10-18 07:39:28,161: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2017-10-18 07:39:28,253: registered with master
[rospy.rosout][INFO] 2017-10-18 07:39:28,254: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-18 07:39:28,264: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-18 07:39:28,275: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-18 07:39:28,389: topic[/state_command] adding connection to [http://10.0.0.116:45821/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:28,402: topic[/state_command] adding connection to [http://10.0.0.116:37775/], count 1
[rospy.internal][INFO] 2017-10-18 07:39:28,405: topic[/state_command] adding connection to [http://10.0.0.116:46200/], count 2
[rospy.internal][INFO] 2017-10-18 07:39:28,406: topic[/state_command] adding connection to [http://10.0.0.116:42879/], count 3
[rospy.internal][INFO] 2017-10-18 07:39:28,421: topic[/state_command] adding connection to [/state_follow_waypoint], count 0
[rospy.internal][INFO] 2017-10-18 07:39:28,425: topic[/state_command] adding connection to [/state_driving_to_cone], count 1
[rospy.internal][INFO] 2017-10-18 07:39:28,430: topic[/state_command] adding connection to [/state_avoiding_obstacle], count 2
[rospy.internal][INFO] 2017-10-18 07:39:28,439: topic[/state_command] adding connection to [/state_driving_away], count 3
[rospy.internal][INFO] 2017-10-18 07:39:28,506: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,081: topic[/mavros/local_position/pose] adding connection to [http://10.0.0.116:35438/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,164: topic[/mavros/setpoint_raw/target_local] adding connection to [http://10.0.0.116:35438/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,208: topic[/mavros/battery] adding connection to [http://10.0.0.116:35438/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,209: topic[/mavros/state] adding connection to [http://10.0.0.116:35438/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,211: topic[/mavlink/from] adding connection to [http://10.0.0.116:35438/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,441: topic[/exec_command] adding connection to [/exec], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,448: topic[/state_command] adding connection to [http://10.0.0.116:38160/], count 4
[rospy.internal][INFO] 2017-10-18 07:39:29,489: topic[/mavros/mission/waypoints] adding connection to [http://10.0.0.116:35438/], count 0
[rospy.internal][INFO] 2017-10-18 07:39:29,640: topic[/mavros/rc/override] adding connection to [/mavros], count 0
[rosout][INFO] 2017-10-18 07:39:33,132: /state_driving_to_cone MsgId 46 detected. WP item # 185
[rospy.core][INFO] 2017-10-18 07:41:28,182: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2017-10-18 07:41:28,400: Unable to initiate TCP/IP socket to 10.0.0.116:38107 (http://10.0.0.116:45821/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-18 07:41:28,459: Unable to initiate TCP/IP socket to 10.0.0.116:38279 (http://10.0.0.116:42879/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-18 07:41:28,459: Unable to initiate TCP/IP socket to 10.0.0.116:44934 (http://10.0.0.116:37775/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:41:28,471: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-18 07:41:28,474: topic[/mavros/rc/override] removing connection to /mavros
[rospy.internal][INFO] 2017-10-18 07:41:28,476: topic[/state_command] removing connection to /state_follow_waypoint
[rospy.internal][INFO] 2017-10-18 07:41:28,488: topic[/state_command] removing connection to /state_driving_to_cone
[rospy.internal][INFO] 2017-10-18 07:41:28,490: topic[/state_command] removing connection to /state_avoiding_obstacle
[rospy.internal][INFO] 2017-10-18 07:41:28,491: topic[/state_command] removing connection to /state_driving_away
[rospy.internal][INFO] 2017-10-18 07:41:28,492: topic[/exec_command] removing connection to /exec
[rospy.internal][ERROR] 2017-10-18 07:41:28,499: Unable to initiate TCP/IP socket to 10.0.0.116:42685 (http://10.0.0.116:46200/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2017-10-18 07:41:28,500: Unable to initiate TCP/IP socket to 10.0.0.116:39504 (http://10.0.0.116:38160/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2017-10-18 07:41:28,501: topic[/mavros/mission/waypoints] removing connection to http://10.0.0.116:35438/
[rospy.internal][INFO] 2017-10-18 07:41:28,502: topic[/mavros/state] removing connection to http://10.0.0.116:35438/
[rospy.internal][INFO] 2017-10-18 07:41:28,502: topic[/mavlink/from] removing connection to http://10.0.0.116:35438/
[rospy.internal][INFO] 2017-10-18 07:41:28,503: topic[/mavros/local_position/pose] removing connection to http://10.0.0.116:35438/
[rospy.internal][INFO] 2017-10-18 07:41:28,503: topic[/mavros/battery] removing connection to http://10.0.0.116:35438/
[rospy.internal][INFO] 2017-10-18 07:41:28,504: topic[/state_command] removing connection to http://10.0.0.116:45821/
[rospy.internal][INFO] 2017-10-18 07:41:28,504: topic[/state_command] removing connection to http://10.0.0.116:37775/
[rospy.internal][INFO] 2017-10-18 07:41:28,504: topic[/state_command] removing connection to http://10.0.0.116:46200/
[rospy.internal][INFO] 2017-10-18 07:41:28,505: topic[/state_command] removing connection to http://10.0.0.116:42879/
[rospy.internal][INFO] 2017-10-18 07:41:28,505: topic[/state_command] removing connection to http://10.0.0.116:38160/
[rospy.internal][INFO] 2017-10-18 07:41:28,506: topic[/mavros/setpoint_raw/target_local] removing connection to http://10.0.0.116:35438/
[rospy.impl.masterslave][INFO] 2017-10-18 07:41:28,510: signal-2
[rospy.core][INFO] 2017-10-18 07:41:28,826: signal_shutdown [atexit]
